// =============================================================================
// Elysia Panel — Contrat gRPC interne entre le Backend (NestJS) et
// Elysia Node (daemon Go, un exemplaire par serveur physique).
// Ce fichier est la source de vérité : le Backend le consomme via
// @grpc/proto-loader, le daemon Go génère son code avec protoc-gen-go-grpc.
// Transport : mTLS uniquement (jamais exposé sans certificat client).
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: elysia.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_elysia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_elysia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,2,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_elysia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *PingResponse) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type SystemStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePct       float64                `protobuf:"fixed64,1,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	MemoryUsedMb      int64                  `protobuf:"varint,2,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryTotalMb     int64                  `protobuf:"varint,3,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	DiskUsedMb        int64                  `protobuf:"varint,4,opt,name=disk_used_mb,json=diskUsedMb,proto3" json:"disk_used_mb,omitempty"`
	DiskTotalMb       int64                  `protobuf:"varint,5,opt,name=disk_total_mb,json=diskTotalMb,proto3" json:"disk_total_mb,omitempty"`
	ContainersRunning int32                  `protobuf:"varint,6,opt,name=containers_running,json=containersRunning,proto3" json:"containers_running,omitempty"`
	ContainersTotal   int32                  `protobuf:"varint,7,opt,name=containers_total,json=containersTotal,proto3" json:"containers_total,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	mi := &file_elysia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{3}
}

func (x *SystemStatsResponse) GetCpuUsagePct() float64 {
	if x != nil {
		return x.CpuUsagePct
	}
	return 0
}

func (x *SystemStatsResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *SystemStatsResponse) GetMemoryTotalMb() int64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *SystemStatsResponse) GetDiskUsedMb() int64 {
	if x != nil {
		return x.DiskUsedMb
	}
	return 0
}

func (x *SystemStatsResponse) GetDiskTotalMb() int64 {
	if x != nil {
		return x.DiskTotalMb
	}
	return 0
}

func (x *SystemStatsResponse) GetContainersRunning() int32 {
	if x != nil {
		return x.ContainersRunning
	}
	return 0
}

func (x *SystemStatsResponse) GetContainersTotal() int32 {
	if x != nil {
		return x.ContainersTotal
	}
	return 0
}

type CreateServerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid     string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	DockerImage    string                 `protobuf:"bytes,2,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	StartupCommand string                 `protobuf:"bytes,3,opt,name=startup_command,json=startupCommand,proto3" json:"startup_command,omitempty"`
	CpuLimitPct    int32                  `protobuf:"varint,4,opt,name=cpu_limit_pct,json=cpuLimitPct,proto3" json:"cpu_limit_pct,omitempty"`
	MemoryLimitMb  int64                  `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	DiskLimitMb    int64                  `protobuf:"varint,6,opt,name=disk_limit_mb,json=diskLimitMb,proto3" json:"disk_limit_mb,omitempty"`
	SwapLimitMb    int64                  `protobuf:"varint,7,opt,name=swap_limit_mb,json=swapLimitMb,proto3" json:"swap_limit_mb,omitempty"`
	IoWeight       int32                  `protobuf:"varint,8,opt,name=io_weight,json=ioWeight,proto3" json:"io_weight,omitempty"`
	Environment    map[string]string      `protobuf:"bytes,9,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports          []*PortMapping         `protobuf:"bytes,10,rep,name=ports,proto3" json:"ports,omitempty"`
	InstallScript  string                 `protobuf:"bytes,11,opt,name=install_script,json=installScript,proto3" json:"install_script,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_elysia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{4}
}

func (x *CreateServerRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *CreateServerRequest) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *CreateServerRequest) GetStartupCommand() string {
	if x != nil {
		return x.StartupCommand
	}
	return ""
}

func (x *CreateServerRequest) GetCpuLimitPct() int32 {
	if x != nil {
		return x.CpuLimitPct
	}
	return 0
}

func (x *CreateServerRequest) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *CreateServerRequest) GetDiskLimitMb() int64 {
	if x != nil {
		return x.DiskLimitMb
	}
	return 0
}

func (x *CreateServerRequest) GetSwapLimitMb() int64 {
	if x != nil {
		return x.SwapLimitMb
	}
	return 0
}

func (x *CreateServerRequest) GetIoWeight() int32 {
	if x != nil {
		return x.IoWeight
	}
	return 0
}

func (x *CreateServerRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *CreateServerRequest) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *CreateServerRequest) GetInstallScript() string {
	if x != nil {
		return x.InstallScript
	}
	return ""
}

type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp | udp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_elysia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{5}
}

func (x *PortMapping) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PortMapping) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ServerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerIdRequest) Reset() {
	*x = ServerIdRequest{}
	mi := &file_elysia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerIdRequest) ProtoMessage() {}

func (x *ServerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerIdRequest.ProtoReflect.Descriptor instead.
func (*ServerIdRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{6}
}

func (x *ServerIdRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

type ServerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerActionResponse) Reset() {
	*x = ServerActionResponse{}
	mi := &file_elysia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerActionResponse) ProtoMessage() {}

func (x *ServerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerActionResponse.ProtoReflect.Descriptor instead.
func (*ServerActionResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{7}
}

func (x *ServerActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_elysia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{8}
}

func (x *SendCommandRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *SendCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ServerStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid     string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	CpuUsagePct    float64                `protobuf:"fixed64,2,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	MemoryUsedMb   int64                  `protobuf:"varint,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	DiskUsedMb     int64                  `protobuf:"varint,4,opt,name=disk_used_mb,json=diskUsedMb,proto3" json:"disk_used_mb,omitempty"`
	NetworkRxBytes int64                  `protobuf:"varint,5,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes int64                  `protobuf:"varint,6,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	State          string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"` // running|stopped|crashed
	UptimeSeconds  int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerStatsResponse) Reset() {
	*x = ServerStatsResponse{}
	mi := &file_elysia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatsResponse) ProtoMessage() {}

func (x *ServerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatsResponse.ProtoReflect.Descriptor instead.
func (*ServerStatsResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{9}
}

func (x *ServerStatsResponse) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *ServerStatsResponse) GetCpuUsagePct() float64 {
	if x != nil {
		return x.CpuUsagePct
	}
	return 0
}

func (x *ServerStatsResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *ServerStatsResponse) GetDiskUsedMb() int64 {
	if x != nil {
		return x.DiskUsedMb
	}
	return 0
}

func (x *ServerStatsResponse) GetNetworkRxBytes() int64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ServerStatsResponse) GetNetworkTxBytes() int64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *ServerStatsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ServerStatsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ConsoleLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Stream        string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"` // stdout|stderr|system
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleLine) Reset() {
	*x = ConsoleLine{}
	mi := &file_elysia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleLine) ProtoMessage() {}

func (x *ConsoleLine) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleLine.ProtoReflect.Descriptor instead.
func (*ConsoleLine) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{10}
}

func (x *ConsoleLine) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *ConsoleLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *ConsoleLine) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ConsoleLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_elysia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{11}
}

func (x *ListFilesRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,2,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModifiedAtMs  int64                  `protobuf:"varint,4,opt,name=modified_at_ms,json=modifiedAtMs,proto3" json:"modified_at_ms,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_elysia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{12}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileEntry) GetModifiedAtMs() int64 {
	if x != nil {
		return x.ModifiedAtMs
	}
	return 0
}

func (x *FileEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_elysia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{13}
}

func (x *ListFilesResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_elysia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{14}
}

func (x *FileRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContentResponse) Reset() {
	*x = FileContentResponse{}
	mi := &file_elysia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContentResponse) ProtoMessage() {}

func (x *FileContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContentResponse.ProtoReflect.Descriptor instead.
func (*FileContentResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{15}
}

func (x *FileContentResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileContentResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_elysia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{16}
}

func (x *WriteFileRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileActionResponse) Reset() {
	*x = FileActionResponse{}
	mi := &file_elysia_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileActionResponse) ProtoMessage() {}

func (x *FileActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileActionResponse.ProtoReflect.Descriptor instead.
func (*FileActionResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{17}
}

func (x *FileActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	FromPath      string                 `protobuf:"bytes,2,opt,name=from_path,json=fromPath,proto3" json:"from_path,omitempty"`
	ToPath        string                 `protobuf:"bytes,3,opt,name=to_path,json=toPath,proto3" json:"to_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_elysia_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{18}
}

func (x *RenameFileRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *RenameFileRequest) GetFromPath() string {
	if x != nil {
		return x.FromPath
	}
	return ""
}

func (x *RenameFileRequest) GetToPath() string {
	if x != nil {
		return x.ToPath
	}
	return ""
}

type CompressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	ArchiveName   string                 `protobuf:"bytes,3,opt,name=archive_name,json=archiveName,proto3" json:"archive_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressRequest) Reset() {
	*x = CompressRequest{}
	mi := &file_elysia_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressRequest) ProtoMessage() {}

func (x *CompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressRequest.ProtoReflect.Descriptor instead.
func (*CompressRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{19}
}

func (x *CompressRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *CompressRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *CompressRequest) GetArchiveName() string {
	if x != nil {
		return x.ArchiveName
	}
	return ""
}

type CreateBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	BackupId      string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	Driver        string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"` // LOCAL|S3|CLOUDFLARE_R2|BACKBLAZE_B2|MINIO|SFTP|FTP
	DriverConfig  map[string]string      `protobuf:"bytes,4,rep,name=driver_config,json=driverConfig,proto3" json:"driver_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_elysia_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{20}
}

func (x *CreateBackupRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *CreateBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *CreateBackupRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CreateBackupRequest) GetDriverConfig() map[string]string {
	if x != nil {
		return x.DriverConfig
	}
	return nil
}

type RestoreBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	BackupId      string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	RemotePath    string                 `protobuf:"bytes,3,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Driver        string                 `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	DriverConfig  map[string]string      `protobuf:"bytes,5,rep,name=driver_config,json=driverConfig,proto3" json:"driver_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_elysia_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{21}
}

func (x *RestoreBackupRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *RestoreBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *RestoreBackupRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *RestoreBackupRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *RestoreBackupRequest) GetDriverConfig() map[string]string {
	if x != nil {
		return x.DriverConfig
	}
	return nil
}

type BackupIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	BackupId      string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	RemotePath    string                 `protobuf:"bytes,3,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Driver        string                 `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	DriverConfig  map[string]string      `protobuf:"bytes,5,rep,name=driver_config,json=driverConfig,proto3" json:"driver_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupIdRequest) Reset() {
	*x = BackupIdRequest{}
	mi := &file_elysia_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupIdRequest) ProtoMessage() {}

func (x *BackupIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupIdRequest.ProtoReflect.Descriptor instead.
func (*BackupIdRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{22}
}

func (x *BackupIdRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *BackupIdRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupIdRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *BackupIdRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *BackupIdRequest) GetDriverConfig() map[string]string {
	if x != nil {
		return x.DriverConfig
	}
	return nil
}

type BackupActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupActionResponse) Reset() {
	*x = BackupActionResponse{}
	mi := &file_elysia_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupActionResponse) ProtoMessage() {}

func (x *BackupActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupActionResponse.ProtoReflect.Descriptor instead.
func (*BackupActionResponse) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{23}
}

func (x *BackupActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BackupActionResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BackupActionResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type TransferRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid            string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	TargetNodeGrpcAddress string                 `protobuf:"bytes,2,opt,name=target_node_grpc_address,json=targetNodeGrpcAddress,proto3" json:"target_node_grpc_address,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_elysia_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{24}
}

func (x *TransferRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *TransferRequest) GetTargetNodeGrpcAddress() string {
	if x != nil {
		return x.TargetNodeGrpcAddress
	}
	return ""
}

type TransferProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BytesTransferred int64                  `protobuf:"varint,1,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	BytesTotal       int64                  `protobuf:"varint,2,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	Completed        bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	Error            string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferProgress) Reset() {
	*x = TransferProgress{}
	mi := &file_elysia_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProgress) ProtoMessage() {}

func (x *TransferProgress) ProtoReflect() protoreflect.Message {
	mi := &file_elysia_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProgress.ProtoReflect.Descriptor instead.
func (*TransferProgress) Descriptor() ([]byte, []int) {
	return file_elysia_proto_rawDescGZIP(), []int{25}
}

func (x *TransferProgress) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *TransferProgress) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *TransferProgress) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TransferProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_elysia_proto protoreflect.FileDescriptor

const file_elysia_proto_rawDesc = "" +
	"\n" +
	"\felysia.proto\x12\x0eelysia.node.v1\"\a\n" +
	"\x05Empty\"#\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"G\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12!\n" +
	"\fnode_version\x18\x02 \x01(\tR\vnodeVersion\"\xa7\x02\n" +
	"\x13SystemStatsResponse\x12\"\n" +
	"\rcpu_usage_pct\x18\x01 \x01(\x01R\vcpuUsagePct\x12$\n" +
	"\x0ememory_used_mb\x18\x02 \x01(\x03R\fmemoryUsedMb\x12&\n" +
	"\x0fmemory_total_mb\x18\x03 \x01(\x03R\rmemoryTotalMb\x12 \n" +
	"\fdisk_used_mb\x18\x04 \x01(\x03R\n" +
	"diskUsedMb\x12\"\n" +
	"\rdisk_total_mb\x18\x05 \x01(\x03R\vdiskTotalMb\x12-\n" +
	"\x12containers_running\x18\x06 \x01(\x05R\x11containersRunning\x12)\n" +
	"\x10containers_total\x18\a \x01(\x05R\x0fcontainersTotal\"\xa5\x04\n" +
	"\x13CreateServerRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12!\n" +
	"\fdocker_image\x18\x02 \x01(\tR\vdockerImage\x12'\n" +
	"\x0fstartup_command\x18\x03 \x01(\tR\x0estartupCommand\x12\"\n" +
	"\rcpu_limit_pct\x18\x04 \x01(\x05R\vcpuLimitPct\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\x03R\rmemoryLimitMb\x12\"\n" +
	"\rdisk_limit_mb\x18\x06 \x01(\x03R\vdiskLimitMb\x12\"\n" +
	"\rswap_limit_mb\x18\a \x01(\x03R\vswapLimitMb\x12\x1b\n" +
	"\tio_weight\x18\b \x01(\x05R\bioWeight\x12V\n" +
	"\venvironment\x18\t \x03(\v24.elysia.node.v1.CreateServerRequest.EnvironmentEntryR\venvironment\x121\n" +
	"\x05ports\x18\n" +
	" \x03(\v2\x1b.elysia.node.v1.PortMappingR\x05ports\x12%\n" +
	"\x0einstall_script\x18\v \x01(\tR\rinstallScript\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\vPortMapping\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"2\n" +
	"\x0fServerIdRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\"J\n" +
	"\x14ServerActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x12SendCommandRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\xb3\x02\n" +
	"\x13ServerStatsResponse\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\"\n" +
	"\rcpu_usage_pct\x18\x02 \x01(\x01R\vcpuUsagePct\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x03R\fmemoryUsedMb\x12 \n" +
	"\fdisk_used_mb\x18\x04 \x01(\x03R\n" +
	"diskUsedMb\x12(\n" +
	"\x10network_rx_bytes\x18\x05 \x01(\x03R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x06 \x01(\x03R\x0enetworkTxBytes\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\"}\n" +
	"\vConsoleLine\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\"G\n" +
	"\x10ListFilesRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x9b\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fis_directory\x18\x02 \x01(\bR\visDirectory\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12$\n" +
	"\x0emodified_at_ms\x18\x04 \x01(\x03R\fmodifiedAtMs\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\"H\n" +
	"\x11ListFilesResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.elysia.node.v1.FileEntryR\aentries\"B\n" +
	"\vFileRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"M\n" +
	"\x13FileContentResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"a\n" +
	"\x10WriteFileRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"H\n" +
	"\x12FileActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x11RenameFileRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x1b\n" +
	"\tfrom_path\x18\x02 \x01(\tR\bfromPath\x12\x17\n" +
	"\ato_path\x18\x03 \x01(\tR\x06toPath\"k\n" +
	"\x0fCompressRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12!\n" +
	"\farchive_name\x18\x03 \x01(\tR\varchiveName\"\x88\x02\n" +
	"\x13CreateBackupRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12Z\n" +
	"\rdriver_config\x18\x04 \x03(\v25.elysia.node.v1.CreateBackupRequest.DriverConfigEntryR\fdriverConfig\x1a?\n" +
	"\x11DriverConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\x14RestoreBackupRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\x12\x1f\n" +
	"\vremote_path\x18\x03 \x01(\tR\n" +
	"remotePath\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\x12[\n" +
	"\rdriver_config\x18\x05 \x03(\v26.elysia.node.v1.RestoreBackupRequest.DriverConfigEntryR\fdriverConfig\x1a?\n" +
	"\x11DriverConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x02\n" +
	"\x0fBackupIdRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\x12\x1f\n" +
	"\vremote_path\x18\x03 \x01(\tR\n" +
	"remotePath\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\x12V\n" +
	"\rdriver_config\x18\x05 \x03(\v21.elysia.node.v1.BackupIdRequest.DriverConfigEntryR\fdriverConfig\x1a?\n" +
	"\x11DriverConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x14BackupActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"k\n" +
	"\x0fTransferRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x127\n" +
	"\x18target_node_grpc_address\x18\x02 \x01(\tR\x15targetNodeGrpcAddress\"\x94\x01\n" +
	"\x10TransferProgress\x12+\n" +
	"\x11bytes_transferred\x18\x01 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vbytes_total\x18\x02 \x01(\x03R\n" +
	"bytesTotal\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xa9\x11\n" +
	"\vNodeService\x12A\n" +
	"\x04Ping\x12\x1b.elysia.node.v1.PingRequest\x1a\x1c.elysia.node.v1.PingResponse\x12L\n" +
	"\x0eGetSystemStats\x12\x15.elysia.node.v1.Empty\x1a#.elysia.node.v1.SystemStatsResponse\x12Y\n" +
	"\fCreateServer\x12#.elysia.node.v1.CreateServerRequest\x1a$.elysia.node.v1.ServerActionResponse\x12T\n" +
	"\vStartServer\x12\x1f.elysia.node.v1.ServerIdRequest\x1a$.elysia.node.v1.ServerActionResponse\x12S\n" +
	"\n" +
	"StopServer\x12\x1f.elysia.node.v1.ServerIdRequest\x1a$.elysia.node.v1.ServerActionResponse\x12V\n" +
	"\rRestartServer\x12\x1f.elysia.node.v1.ServerIdRequest\x1a$.elysia.node.v1.ServerActionResponse\x12S\n" +
	"\n" +
	"KillServer\x12\x1f.elysia.node.v1.ServerIdRequest\x1a$.elysia.node.v1.ServerActionResponse\x12U\n" +
	"\fDeleteServer\x12\x1f.elysia.node.v1.ServerIdRequest\x1a$.elysia.node.v1.ServerActionResponse\x12\\\n" +
	"\x0fReinstallServer\x12#.elysia.node.v1.CreateServerRequest\x1a$.elysia.node.v1.ServerActionResponse\x12W\n" +
	"\vSendCommand\x12\".elysia.node.v1.SendCommandRequest\x1a$.elysia.node.v1.ServerActionResponse\x12V\n" +
	"\x0eGetServerStats\x12\x1f.elysia.node.v1.ServerIdRequest\x1a#.elysia.node.v1.ServerStatsResponse\x12O\n" +
	"\rStreamConsole\x12\x1f.elysia.node.v1.ServerIdRequest\x1a\x1b.elysia.node.v1.ConsoleLine0\x01\x12U\n" +
	"\vStreamStats\x12\x1f.elysia.node.v1.ServerIdRequest\x1a#.elysia.node.v1.ServerStatsResponse0\x01\x12P\n" +
	"\tListFiles\x12 .elysia.node.v1.ListFilesRequest\x1a!.elysia.node.v1.ListFilesResponse\x12L\n" +
	"\bReadFile\x12\x1b.elysia.node.v1.FileRequest\x1a#.elysia.node.v1.FileContentResponse\x12Q\n" +
	"\tWriteFile\x12 .elysia.node.v1.WriteFileRequest\x1a\".elysia.node.v1.FileActionResponse\x12M\n" +
	"\n" +
	"DeleteFile\x12\x1b.elysia.node.v1.FileRequest\x1a\".elysia.node.v1.FileActionResponse\x12S\n" +
	"\n" +
	"RenameFile\x12!.elysia.node.v1.RenameFileRequest\x1a\".elysia.node.v1.FileActionResponse\x12R\n" +
	"\x0fCreateDirectory\x12\x1b.elysia.node.v1.FileRequest\x1a\".elysia.node.v1.FileActionResponse\x12T\n" +
	"\rCompressFiles\x12\x1f.elysia.node.v1.CompressRequest\x1a\".elysia.node.v1.FileActionResponse\x12Q\n" +
	"\x0eDecompressFile\x12\x1b.elysia.node.v1.FileRequest\x1a\".elysia.node.v1.FileActionResponse\x12Y\n" +
	"\fCreateBackup\x12#.elysia.node.v1.CreateBackupRequest\x1a$.elysia.node.v1.BackupActionResponse\x12[\n" +
	"\rRestoreBackup\x12$.elysia.node.v1.RestoreBackupRequest\x1a$.elysia.node.v1.BackupActionResponse\x12U\n" +
	"\fDeleteBackup\x12\x1f.elysia.node.v1.BackupIdRequest\x1a$.elysia.node.v1.BackupActionResponse\x12R\n" +
	"\vTransferOut\x12\x1f.elysia.node.v1.TransferRequest\x1a .elysia.node.v1.TransferProgress0\x01\x12Q\n" +
	"\n" +
	"TransferIn\x12\x1f.elysia.node.v1.TransferRequest\x1a .elysia.node.v1.TransferProgress0\x01B2Z0github.com/elysia-panel/elysia-node/proto;nodev1b\x06proto3"

var (
	file_elysia_proto_rawDescOnce sync.Once
	file_elysia_proto_rawDescData []byte
)

func file_elysia_proto_rawDescGZIP() []byte {
	file_elysia_proto_rawDescOnce.Do(func() {
		file_elysia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elysia_proto_rawDesc), len(file_elysia_proto_rawDesc)))
	})
	return file_elysia_proto_rawDescData
}

var file_elysia_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_elysia_proto_goTypes = []any{
	(*Empty)(nil),                // 0: elysia.node.v1.Empty
	(*PingRequest)(nil),          // 1: elysia.node.v1.PingRequest
	(*PingResponse)(nil),         // 2: elysia.node.v1.PingResponse
	(*SystemStatsResponse)(nil),  // 3: elysia.node.v1.SystemStatsResponse
	(*CreateServerRequest)(nil),  // 4: elysia.node.v1.CreateServerRequest
	(*PortMapping)(nil),          // 5: elysia.node.v1.PortMapping
	(*ServerIdRequest)(nil),      // 6: elysia.node.v1.ServerIdRequest
	(*ServerActionResponse)(nil), // 7: elysia.node.v1.ServerActionResponse
	(*SendCommandRequest)(nil),   // 8: elysia.node.v1.SendCommandRequest
	(*ServerStatsResponse)(nil),  // 9: elysia.node.v1.ServerStatsResponse
	(*ConsoleLine)(nil),          // 10: elysia.node.v1.ConsoleLine
	(*ListFilesRequest)(nil),     // 11: elysia.node.v1.ListFilesRequest
	(*FileEntry)(nil),            // 12: elysia.node.v1.FileEntry
	(*ListFilesResponse)(nil),    // 13: elysia.node.v1.ListFilesResponse
	(*FileRequest)(nil),          // 14: elysia.node.v1.FileRequest
	(*FileContentResponse)(nil),  // 15: elysia.node.v1.FileContentResponse
	(*WriteFileRequest)(nil),     // 16: elysia.node.v1.WriteFileRequest
	(*FileActionResponse)(nil),   // 17: elysia.node.v1.FileActionResponse
	(*RenameFileRequest)(nil),    // 18: elysia.node.v1.RenameFileRequest
	(*CompressRequest)(nil),      // 19: elysia.node.v1.CompressRequest
	(*CreateBackupRequest)(nil),  // 20: elysia.node.v1.CreateBackupRequest
	(*RestoreBackupRequest)(nil), // 21: elysia.node.v1.RestoreBackupRequest
	(*BackupIdRequest)(nil),      // 22: elysia.node.v1.BackupIdRequest
	(*BackupActionResponse)(nil), // 23: elysia.node.v1.BackupActionResponse
	(*TransferRequest)(nil),      // 24: elysia.node.v1.TransferRequest
	(*TransferProgress)(nil),     // 25: elysia.node.v1.TransferProgress
	nil,                          // 26: elysia.node.v1.CreateServerRequest.EnvironmentEntry
	nil,                          // 27: elysia.node.v1.CreateBackupRequest.DriverConfigEntry
	nil,                          // 28: elysia.node.v1.RestoreBackupRequest.DriverConfigEntry
	nil,                          // 29: elysia.node.v1.BackupIdRequest.DriverConfigEntry
}
var file_elysia_proto_depIdxs = []int32{
	26, // 0: elysia.node.v1.CreateServerRequest.environment:type_name -> elysia.node.v1.CreateServerRequest.EnvironmentEntry
	5,  // 1: elysia.node.v1.CreateServerRequest.ports:type_name -> elysia.node.v1.PortMapping
	12, // 2: elysia.node.v1.ListFilesResponse.entries:type_name -> elysia.node.v1.FileEntry
	27, // 3: elysia.node.v1.CreateBackupRequest.driver_config:type_name -> elysia.node.v1.CreateBackupRequest.DriverConfigEntry
	28, // 4: elysia.node.v1.RestoreBackupRequest.driver_config:type_name -> elysia.node.v1.RestoreBackupRequest.DriverConfigEntry
	29, // 5: elysia.node.v1.BackupIdRequest.driver_config:type_name -> elysia.node.v1.BackupIdRequest.DriverConfigEntry
	1,  // 6: elysia.node.v1.NodeService.Ping:input_type -> elysia.node.v1.PingRequest
	0,  // 7: elysia.node.v1.NodeService.GetSystemStats:input_type -> elysia.node.v1.Empty
	4,  // 8: elysia.node.v1.NodeService.CreateServer:input_type -> elysia.node.v1.CreateServerRequest
	6,  // 9: elysia.node.v1.NodeService.StartServer:input_type -> elysia.node.v1.ServerIdRequest
	6,  // 10: elysia.node.v1.NodeService.StopServer:input_type -> elysia.node.v1.ServerIdRequest
	6,  // 11: elysia.node.v1.NodeService.RestartServer:input_type -> elysia.node.v1.ServerIdRequest
	6,  // 12: elysia.node.v1.NodeService.KillServer:input_type -> elysia.node.v1.ServerIdRequest
	6,  // 13: elysia.node.v1.NodeService.DeleteServer:input_type -> elysia.node.v1.ServerIdRequest
	4,  // 14: elysia.node.v1.NodeService.ReinstallServer:input_type -> elysia.node.v1.CreateServerRequest
	8,  // 15: elysia.node.v1.NodeService.SendCommand:input_type -> elysia.node.v1.SendCommandRequest
	6,  // 16: elysia.node.v1.NodeService.GetServerStats:input_type -> elysia.node.v1.ServerIdRequest
	6,  // 17: elysia.node.v1.NodeService.StreamConsole:input_type -> elysia.node.v1.ServerIdRequest
	6,  // 18: elysia.node.v1.NodeService.StreamStats:input_type -> elysia.node.v1.ServerIdRequest
	11, // 19: elysia.node.v1.NodeService.ListFiles:input_type -> elysia.node.v1.ListFilesRequest
	14, // 20: elysia.node.v1.NodeService.ReadFile:input_type -> elysia.node.v1.FileRequest
	16, // 21: elysia.node.v1.NodeService.WriteFile:input_type -> elysia.node.v1.WriteFileRequest
	14, // 22: elysia.node.v1.NodeService.DeleteFile:input_type -> elysia.node.v1.FileRequest
	18, // 23: elysia.node.v1.NodeService.RenameFile:input_type -> elysia.node.v1.RenameFileRequest
	14, // 24: elysia.node.v1.NodeService.CreateDirectory:input_type -> elysia.node.v1.FileRequest
	19, // 25: elysia.node.v1.NodeService.CompressFiles:input_type -> elysia.node.v1.CompressRequest
	14, // 26: elysia.node.v1.NodeService.DecompressFile:input_type -> elysia.node.v1.FileRequest
	20, // 27: elysia.node.v1.NodeService.CreateBackup:input_type -> elysia.node.v1.CreateBackupRequest
	21, // 28: elysia.node.v1.NodeService.RestoreBackup:input_type -> elysia.node.v1.RestoreBackupRequest
	22, // 29: elysia.node.v1.NodeService.DeleteBackup:input_type -> elysia.node.v1.BackupIdRequest
	24, // 30: elysia.node.v1.NodeService.TransferOut:input_type -> elysia.node.v1.TransferRequest
	24, // 31: elysia.node.v1.NodeService.TransferIn:input_type -> elysia.node.v1.TransferRequest
	2,  // 32: elysia.node.v1.NodeService.Ping:output_type -> elysia.node.v1.PingResponse
	3,  // 33: elysia.node.v1.NodeService.GetSystemStats:output_type -> elysia.node.v1.SystemStatsResponse
	7,  // 34: elysia.node.v1.NodeService.CreateServer:output_type -> elysia.node.v1.ServerActionResponse
	7,  // 35: elysia.node.v1.NodeService.StartServer:output_type -> elysia.node.v1.ServerActionResponse
	7,  // 36: elysia.node.v1.NodeService.StopServer:output_type -> elysia.node.v1.ServerActionResponse
	7,  // 37: elysia.node.v1.NodeService.RestartServer:output_type -> elysia.node.v1.ServerActionResponse
	7,  // 38: elysia.node.v1.NodeService.KillServer:output_type -> elysia.node.v1.ServerActionResponse
	7,  // 39: elysia.node.v1.NodeService.DeleteServer:output_type -> elysia.node.v1.ServerActionResponse
	7,  // 40: elysia.node.v1.NodeService.ReinstallServer:output_type -> elysia.node.v1.ServerActionResponse
	7,  // 41: elysia.node.v1.NodeService.SendCommand:output_type -> elysia.node.v1.ServerActionResponse
	9,  // 42: elysia.node.v1.NodeService.GetServerStats:output_type -> elysia.node.v1.ServerStatsResponse
	10, // 43: elysia.node.v1.NodeService.StreamConsole:output_type -> elysia.node.v1.ConsoleLine
	9,  // 44: elysia.node.v1.NodeService.StreamStats:output_type -> elysia.node.v1.ServerStatsResponse
	13, // 45: elysia.node.v1.NodeService.ListFiles:output_type -> elysia.node.v1.ListFilesResponse
	15, // 46: elysia.node.v1.NodeService.ReadFile:output_type -> elysia.node.v1.FileContentResponse
	17, // 47: elysia.node.v1.NodeService.WriteFile:output_type -> elysia.node.v1.FileActionResponse
	17, // 48: elysia.node.v1.NodeService.DeleteFile:output_type -> elysia.node.v1.FileActionResponse
	17, // 49: elysia.node.v1.NodeService.RenameFile:output_type -> elysia.node.v1.FileActionResponse
	17, // 50: elysia.node.v1.NodeService.CreateDirectory:output_type -> elysia.node.v1.FileActionResponse
	17, // 51: elysia.node.v1.NodeService.CompressFiles:output_type -> elysia.node.v1.FileActionResponse
	17, // 52: elysia.node.v1.NodeService.DecompressFile:output_type -> elysia.node.v1.FileActionResponse
	23, // 53: elysia.node.v1.NodeService.CreateBackup:output_type -> elysia.node.v1.BackupActionResponse
	23, // 54: elysia.node.v1.NodeService.RestoreBackup:output_type -> elysia.node.v1.BackupActionResponse
	23, // 55: elysia.node.v1.NodeService.DeleteBackup:output_type -> elysia.node.v1.BackupActionResponse
	25, // 56: elysia.node.v1.NodeService.TransferOut:output_type -> elysia.node.v1.TransferProgress
	25, // 57: elysia.node.v1.NodeService.TransferIn:output_type -> elysia.node.v1.TransferProgress
	32, // [32:58] is the sub-list for method output_type
	6,  // [6:32] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_elysia_proto_init() }
func file_elysia_proto_init() {
	if File_elysia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elysia_proto_rawDesc), len(file_elysia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elysia_proto_goTypes,
		DependencyIndexes: file_elysia_proto_depIdxs,
		MessageInfos:      file_elysia_proto_msgTypes,
	}.Build()
	File_elysia_proto = out.File
	file_elysia_proto_goTypes = nil
	file_elysia_proto_depIdxs = nil
}
