// =============================================================================
// Elysia Panel — Contrat gRPC interne entre le Backend (NestJS) et
// Elysia Node (daemon Go, un exemplaire par serveur physique).
// Ce fichier est la source de vérité : le Backend le consomme via
// @grpc/proto-loader, le daemon Go génère son code avec protoc-gen-go-grpc.
// Transport : mTLS uniquement (jamais exposé sans certificat client).
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: elysia.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Ping_FullMethodName            = "/elysia.node.v1.NodeService/Ping"
	NodeService_GetSystemStats_FullMethodName  = "/elysia.node.v1.NodeService/GetSystemStats"
	NodeService_CreateServer_FullMethodName    = "/elysia.node.v1.NodeService/CreateServer"
	NodeService_StartServer_FullMethodName     = "/elysia.node.v1.NodeService/StartServer"
	NodeService_StopServer_FullMethodName      = "/elysia.node.v1.NodeService/StopServer"
	NodeService_RestartServer_FullMethodName   = "/elysia.node.v1.NodeService/RestartServer"
	NodeService_KillServer_FullMethodName      = "/elysia.node.v1.NodeService/KillServer"
	NodeService_DeleteServer_FullMethodName    = "/elysia.node.v1.NodeService/DeleteServer"
	NodeService_ReinstallServer_FullMethodName = "/elysia.node.v1.NodeService/ReinstallServer"
	NodeService_SendCommand_FullMethodName     = "/elysia.node.v1.NodeService/SendCommand"
	NodeService_GetServerStats_FullMethodName  = "/elysia.node.v1.NodeService/GetServerStats"
	NodeService_StreamConsole_FullMethodName   = "/elysia.node.v1.NodeService/StreamConsole"
	NodeService_StreamStats_FullMethodName     = "/elysia.node.v1.NodeService/StreamStats"
	NodeService_ListFiles_FullMethodName       = "/elysia.node.v1.NodeService/ListFiles"
	NodeService_ReadFile_FullMethodName        = "/elysia.node.v1.NodeService/ReadFile"
	NodeService_WriteFile_FullMethodName       = "/elysia.node.v1.NodeService/WriteFile"
	NodeService_DeleteFile_FullMethodName      = "/elysia.node.v1.NodeService/DeleteFile"
	NodeService_RenameFile_FullMethodName      = "/elysia.node.v1.NodeService/RenameFile"
	NodeService_CompressFiles_FullMethodName   = "/elysia.node.v1.NodeService/CompressFiles"
	NodeService_DecompressFile_FullMethodName  = "/elysia.node.v1.NodeService/DecompressFile"
	NodeService_CreateBackup_FullMethodName    = "/elysia.node.v1.NodeService/CreateBackup"
	NodeService_RestoreBackup_FullMethodName   = "/elysia.node.v1.NodeService/RestoreBackup"
	NodeService_DeleteBackup_FullMethodName    = "/elysia.node.v1.NodeService/DeleteBackup"
	NodeService_TransferOut_FullMethodName     = "/elysia.node.v1.NodeService/TransferOut"
	NodeService_TransferIn_FullMethodName      = "/elysia.node.v1.NodeService/TransferIn"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Cycle de vie du daemon / du node
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetSystemStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStatsResponse, error)
	// Cycle de vie des serveurs (conteneurs Docker)
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	StartServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	StopServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	RestartServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	KillServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	DeleteServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	ReinstallServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*ServerActionResponse, error)
	GetServerStats(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerStatsResponse, error)
	// Streaming temps réel (logs console + stats), relayé par le Backend au WS client
	StreamConsole(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleLine], error)
	StreamStats(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStatsResponse], error)
	// Fichiers
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	ReadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileContentResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*FileActionResponse, error)
	DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileActionResponse, error)
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*FileActionResponse, error)
	CompressFiles(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*FileActionResponse, error)
	DecompressFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileActionResponse, error)
	// Sauvegardes
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupActionResponse, error)
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*BackupActionResponse, error)
	DeleteBackup(ctx context.Context, in *BackupIdRequest, opts ...grpc.CallOption) (*BackupActionResponse, error)
	// Migration entre nodes
	TransferOut(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferProgress], error)
	TransferIn(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferProgress], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NodeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetSystemStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatsResponse)
	err := c.cc.Invoke(ctx, NodeService_GetSystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_CreateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StartServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_StartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StopServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_StopServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestartServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_RestartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) KillServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_KillServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteServer(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReinstallServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_ReinstallServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*ServerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetServerStats(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatsResponse)
	err := c.cc.Invoke(ctx, NodeService_GetServerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamConsole(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_StreamConsole_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServerIdRequest, ConsoleLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamConsoleClient = grpc.ServerStreamingClient[ConsoleLine]

func (c *nodeServiceClient) StreamStats(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStatsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_StreamStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServerIdRequest, ServerStatsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamStatsClient = grpc.ServerStreamingClient[ServerStatsResponse]

func (c *nodeServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, NodeService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileContentResponse)
	err := c.cc.Invoke(ctx, NodeService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*FileActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileActionResponse)
	err := c.cc.Invoke(ctx, NodeService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileActionResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*FileActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileActionResponse)
	err := c.cc.Invoke(ctx, NodeService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CompressFiles(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*FileActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileActionResponse)
	err := c.cc.Invoke(ctx, NodeService_CompressFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DecompressFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileActionResponse)
	err := c.cc.Invoke(ctx, NodeService_DecompressFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupActionResponse)
	err := c.cc.Invoke(ctx, NodeService_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*BackupActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupActionResponse)
	err := c.cc.Invoke(ctx, NodeService_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteBackup(ctx context.Context, in *BackupIdRequest, opts ...grpc.CallOption) (*BackupActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupActionResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) TransferOut(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_TransferOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransferRequest, TransferProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TransferOutClient = grpc.ServerStreamingClient[TransferProgress]

func (c *nodeServiceClient) TransferIn(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[3], NodeService_TransferIn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransferRequest, TransferProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TransferInClient = grpc.ServerStreamingClient[TransferProgress]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// Cycle de vie du daemon / du node
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetSystemStats(context.Context, *Empty) (*SystemStatsResponse, error)
	// Cycle de vie des serveurs (conteneurs Docker)
	CreateServer(context.Context, *CreateServerRequest) (*ServerActionResponse, error)
	StartServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error)
	StopServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error)
	RestartServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error)
	KillServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error)
	DeleteServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error)
	ReinstallServer(context.Context, *CreateServerRequest) (*ServerActionResponse, error)
	SendCommand(context.Context, *SendCommandRequest) (*ServerActionResponse, error)
	GetServerStats(context.Context, *ServerIdRequest) (*ServerStatsResponse, error)
	// Streaming temps réel (logs console + stats), relayé par le Backend au WS client
	StreamConsole(*ServerIdRequest, grpc.ServerStreamingServer[ConsoleLine]) error
	StreamStats(*ServerIdRequest, grpc.ServerStreamingServer[ServerStatsResponse]) error
	// Fichiers
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ReadFile(context.Context, *FileRequest) (*FileContentResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*FileActionResponse, error)
	DeleteFile(context.Context, *FileRequest) (*FileActionResponse, error)
	RenameFile(context.Context, *RenameFileRequest) (*FileActionResponse, error)
	CompressFiles(context.Context, *CompressRequest) (*FileActionResponse, error)
	DecompressFile(context.Context, *FileRequest) (*FileActionResponse, error)
	// Sauvegardes
	CreateBackup(context.Context, *CreateBackupRequest) (*BackupActionResponse, error)
	RestoreBackup(context.Context, *RestoreBackupRequest) (*BackupActionResponse, error)
	DeleteBackup(context.Context, *BackupIdRequest) (*BackupActionResponse, error)
	// Migration entre nodes
	TransferOut(*TransferRequest, grpc.ServerStreamingServer[TransferProgress]) error
	TransferIn(*TransferRequest, grpc.ServerStreamingServer[TransferProgress]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeServiceServer) GetSystemStats(context.Context, *Empty) (*SystemStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStats not implemented")
}
func (UnimplementedNodeServiceServer) CreateServer(context.Context, *CreateServerRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServer not implemented")
}
func (UnimplementedNodeServiceServer) StartServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartServer not implemented")
}
func (UnimplementedNodeServiceServer) StopServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopServer not implemented")
}
func (UnimplementedNodeServiceServer) RestartServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartServer not implemented")
}
func (UnimplementedNodeServiceServer) KillServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillServer not implemented")
}
func (UnimplementedNodeServiceServer) DeleteServer(context.Context, *ServerIdRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteServer not implemented")
}
func (UnimplementedNodeServiceServer) ReinstallServer(context.Context, *CreateServerRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReinstallServer not implemented")
}
func (UnimplementedNodeServiceServer) SendCommand(context.Context, *SendCommandRequest) (*ServerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedNodeServiceServer) GetServerStats(context.Context, *ServerIdRequest) (*ServerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStats not implemented")
}
func (UnimplementedNodeServiceServer) StreamConsole(*ServerIdRequest, grpc.ServerStreamingServer[ConsoleLine]) error {
	return status.Error(codes.Unimplemented, "method StreamConsole not implemented")
}
func (UnimplementedNodeServiceServer) StreamStats(*ServerIdRequest, grpc.ServerStreamingServer[ServerStatsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStats not implemented")
}
func (UnimplementedNodeServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedNodeServiceServer) ReadFile(context.Context, *FileRequest) (*FileContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedNodeServiceServer) WriteFile(context.Context, *WriteFileRequest) (*FileActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedNodeServiceServer) DeleteFile(context.Context, *FileRequest) (*FileActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedNodeServiceServer) RenameFile(context.Context, *RenameFileRequest) (*FileActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedNodeServiceServer) CompressFiles(context.Context, *CompressRequest) (*FileActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompressFiles not implemented")
}
func (UnimplementedNodeServiceServer) DecompressFile(context.Context, *FileRequest) (*FileActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecompressFile not implemented")
}
func (UnimplementedNodeServiceServer) CreateBackup(context.Context, *CreateBackupRequest) (*BackupActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedNodeServiceServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*BackupActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedNodeServiceServer) DeleteBackup(context.Context, *BackupIdRequest) (*BackupActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedNodeServiceServer) TransferOut(*TransferRequest, grpc.ServerStreamingServer[TransferProgress]) error {
	return status.Error(codes.Unimplemented, "method TransferOut not implemented")
}
func (UnimplementedNodeServiceServer) TransferIn(*TransferRequest, grpc.ServerStreamingServer[TransferProgress]) error {
	return status.Error(codes.Unimplemented, "method TransferIn not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetSystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetSystemStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CreateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StartServer(ctx, req.(*ServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StopServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StopServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StopServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StopServer(ctx, req.(*ServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestartServer(ctx, req.(*ServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_KillServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).KillServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_KillServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).KillServer(ctx, req.(*ServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteServer(ctx, req.(*ServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReinstallServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReinstallServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReinstallServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReinstallServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetServerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetServerStats(ctx, req.(*ServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamConsole_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerIdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamConsole(m, &grpc.GenericServerStream[ServerIdRequest, ConsoleLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamConsoleServer = grpc.ServerStreamingServer[ConsoleLine]

func _NodeService_StreamStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerIdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamStats(m, &grpc.GenericServerStream[ServerIdRequest, ServerStatsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamStatsServer = grpc.ServerStreamingServer[ServerStatsResponse]

func _NodeService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReadFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CompressFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CompressFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CompressFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CompressFiles(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DecompressFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DecompressFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DecompressFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DecompressFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteBackup(ctx, req.(*BackupIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_TransferOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransferRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).TransferOut(m, &grpc.GenericServerStream[TransferRequest, TransferProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TransferOutServer = grpc.ServerStreamingServer[TransferProgress]

func _NodeService_TransferIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransferRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).TransferIn(m, &grpc.GenericServerStream[TransferRequest, TransferProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TransferInServer = grpc.ServerStreamingServer[TransferProgress]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "elysia.node.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _NodeService_Ping_Handler,
		},
		{
			MethodName: "GetSystemStats",
			Handler:    _NodeService_GetSystemStats_Handler,
		},
		{
			MethodName: "CreateServer",
			Handler:    _NodeService_CreateServer_Handler,
		},
		{
			MethodName: "StartServer",
			Handler:    _NodeService_StartServer_Handler,
		},
		{
			MethodName: "StopServer",
			Handler:    _NodeService_StopServer_Handler,
		},
		{
			MethodName: "RestartServer",
			Handler:    _NodeService_RestartServer_Handler,
		},
		{
			MethodName: "KillServer",
			Handler:    _NodeService_KillServer_Handler,
		},
		{
			MethodName: "DeleteServer",
			Handler:    _NodeService_DeleteServer_Handler,
		},
		{
			MethodName: "ReinstallServer",
			Handler:    _NodeService_ReinstallServer_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _NodeService_SendCommand_Handler,
		},
		{
			MethodName: "GetServerStats",
			Handler:    _NodeService_GetServerStats_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _NodeService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _NodeService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _NodeService_WriteFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _NodeService_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _NodeService_RenameFile_Handler,
		},
		{
			MethodName: "CompressFiles",
			Handler:    _NodeService_CompressFiles_Handler,
		},
		{
			MethodName: "DecompressFile",
			Handler:    _NodeService_DecompressFile_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _NodeService_CreateBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _NodeService_RestoreBackup_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _NodeService_DeleteBackup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConsole",
			Handler:       _NodeService_StreamConsole_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamStats",
			Handler:       _NodeService_StreamStats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TransferOut",
			Handler:       _NodeService_TransferOut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TransferIn",
			Handler:       _NodeService_TransferIn_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "elysia.proto",
}
